# Generated by Django 3.2.6 on 2021-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
